version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: NuGet.Commands
    versions:
    - 5.9.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Cake.Core
    versions:
    - 0.38.5
    - 1.0.0
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
