version: '{build}'
image: Visual Studio 2017
build_script:
- ps: .\build.ps1 --target=AppVeyor
test: off
artifacts:
- path: .\artifacts\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: 3pdMYjShRlHSTjimXNoZTiFw8w0F6u9MKOVhtLSyu92c3FhsvJfK4zjSmFxZgY7v
  skip_symbols: false