version: '{build}'
image: Visual Studio 2017
build_script:
- ps: .\build.ps1 --target=AppVeyor
test: off
artifacts:
- path: .\artifacts\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: 97AQa+aHct8sAMSMjSHuVv8VDjdUwFNKErdGaSwxFty4kpgphiZijQVExmQAc/Yb
  skip_symbols: false